### ISSUE TITLE
How to run MWUF best on dataset ml-1M?

### ISSUE THREAD

**Issue by Isuxiz** [nuster1128/RecBole-MetaRec#2]
1. Do I only need to change the parameters mentioned in `RecBole-MetaRec/asset/result/MovieLens-1M.md` and keep other parameters unchanged?
2. Is the name of the `embedding_size` parameter occured in `RecBole-MetaRec/asset/result/MovieLens-1M.md` misspelled? I think you mean the `embedding` parameter under the `# MWUF Parameters` section. And I changed it to guided value.
3. I did nothing but change the yaml file of MWUF according to 1 and 2. After that, I changed the model name and dataset in `quick_start.py` as instructed in the Readme, but the running result is far from the conclusion of the original paper ( The auc on the test set is only about 0.3991. ). Is this as expected? Or am I missing steps?

**Comment by nuster1128** [comment]
Thanks for your issue!

For question 1:
We strongly recommend (1) adjusting environment variables of your own experimental setting (e.g., number of support set, user interaction ranges). (2) tuning the best parameters under your experimental setting, and you can also refers to the tool `param_fine_tune.py` we have provided in our package. That's because different datasets and different experimental settings do correspond to different best hyper parameters and values. Moreover, the fact that a model is good at one circumstance does not mean that it is good at another as well. Therefore, the best parameters we have provided are under our experimental setting, which is aligned for the models we have implemented. 
For question 2:
Thanks for finding it! Acutually, `embedding_size` and `embedding` are same, which are corresponding to the size of embedding layer. We will correct this misspell in the next version.
For question 3:
Actually, I think it is as expected. As I have mentioned above: different datasets and different experimental settings do correspond to different best hyper parameters and values. In order to train and test all the models that we implemented, we conduct the process under a common circumstance, which may not correspond to the original paper of MWUF.

Thanks for your issue again, and sorry for this late reply! I hope this reply will help you.
