### ISSUE TITLE
commit 84412 把dataloader里面需要重写的函数删了，导致代码报错了

### ISSUE THREAD

**Issue by YantongDU** [nuster1128/RecBole-MetaRec#4]
commit 84412 把dataloader里面需要重写的函数删了，导致代码报错了

**Comment by nuster1128** [comment]
Thanks for your issue : ) . Actually in commit 8441224, we have just refined our codes in _metadataloader_ for compatibility a few days ago, because RecBole had a recent update and RecBole-MetaRec is based on RecBole. Before this refinement, it can be runned under RecBole 1.0.1, but fail in RecBole 1.1.1 . After this refinement, it has been compatible with RecBole 1.1.1, and then we do not use RecBole 1.0.1 .
You can update RecBole 1.0.1 to RecBole 1.1.1 and have a try.

**Comment by YantongDU** [comment]
Thanks for your reply. Actually, we clone the source code in the local environment and did not notice the update of RecBole. We will pay attention to this problem in the future.
